# Generated by Django 5.0.2 on 2024-03-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_remove_product_min_stock_product_have_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito_products',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.IntegerField(default=0),
        ),
    ]
