# Generated by Django 5.0.2 on 2024-03-14 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_carrito_products_user'),
        ('ventas', '0007_carrito_products_have_coupon'),
    ]

    operations = [
    ]
