# Generated by Django 5.0.2 on 2024-03-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_merge_20240313_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito_products',
            name='unit_price',
            field=models.IntegerField(default=0),
        ),
    ]
