# Generated by Django 5.0.2 on 2024-03-14 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_carrito_products_unit_price'),
        ('ventas', '0009_sell_history'),
    ]

    operations = [
    ]
